#!/usr/bin/env python3

import os
import sys
import datetime
import getpass
import socket

"""
This Python script combines multiple synonym files from a specified directory into a single output file. 

What it does:
1. Reads all `.txt` files in a given directory that contain synonym sets. Each line in these files is a comma-separated list of synonyms.
2. It ensures that synonym sets with overlapping terms (e.g., "car, automobile" and "automobile, vehicle") are merged into a single line.
3. The program removes duplicate entries and reorders the terms alphabetically within each line for clarity.
4. It writes the combined, deduplicated synonym sets into a new output file with an introductory header.

The output file also contains metadata:
1. A listing of the paths to the files that were combined to create the output file.
2. The timestamp of when it was created.
3. The user/owner that executed the command.
4. The hostname that the command was executed on.

Additionally, the file contains a note warning that the combined synonyms list should be reviewed by a human to ensure the accuracy of the merged synonyms.
"""


def parse_synonym_line(line):
    """
    Parse a synonym line into a set of terms.
    This ensures we can compare synonym lines regardless of term order.
    """
    return set(term.strip() for term in line.split(","))


def merge_synonym_sets(existing_synonyms, new_synonym_set):
    """
    Merges any existing synonym sets that have overlap with the new synonym set.
    """
    to_merge = []

    # Find all synonym sets that overlap with the new set
    for synonym_set in existing_synonyms:
        if not synonym_set.isdisjoint(new_synonym_set):
            to_merge.append(synonym_set)

    # Merge all overlapping sets into a single set
    for synonym_set in to_merge:
        existing_synonyms.remove(synonym_set)
        new_synonym_set.update(synonym_set)

    # Add the newly merged set to the collection
    existing_synonyms.append(new_synonym_set)


def combine_synonym_files_in_directory(directory):
    """
    Combine all synonym files in the specified directory into one, removing duplicates and appending new synonyms.

    :param directory: Directory containing synonym files.
    :return: A list of combined synonym lines, and a list of file paths that were combined.
    """
    combined_synonyms = []
    file_paths = []

    # Scan directory for all .txt files
    for filename in os.listdir(directory):
        if filename.endswith(".txt"):
            file_path = os.path.join(directory, filename)
            file_paths.append(file_path)
            print(f"Processing file: {file_path}")

            with open(file_path, 'r') as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("#"):
                        # Ignore empty lines and comments
                        continue

                    new_synonym_set = parse_synonym_line(line)
                    merge_synonym_sets(combined_synonyms, new_synonym_set)

    # Convert sets back into sorted comma-separated lines
    combined_synonym_lines = [", ".join(sorted(synonym_set)) for synonym_set in combined_synonyms]
    return combined_synonym_lines, file_paths


def write_combined_synonyms(output_file, combined_synonyms, file_paths):
    """
    Write the combined synonym list to a new file with an introductory header and metadata.

    :param output_file: Output file path.
    :param combined_synonyms: List of combined synonym lines.
    :param file_paths: List of paths of the files that were combined.
    """
    # Get metadata: timestamp, user, and hostname
    timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    user = getpass.getuser()
    hostname = socket.gethostname()

    with open(output_file, 'w') as f:
        # Write the introductory header
        f.write("# This file contains combined synonym sets generated by merging multiple synonym files.\n")
        f.write(
            "# Synonym sets with overlapping terms are merged into a single set, and duplicate entries are removed.\n")
        f.write(
            "# Each line contains synonyms, separated by commas, which can be used in Elasticsearch or other search systems.\n")
        f.write("# The lines are automatically deduplicated and sorted for clarity and performance.\n")
        f.write("# Example:\n")
        f.write("# car, automobile, vehicle, auto\n\n")

        # Add warning about human review and possible errors
        f.write("# IMPORTANT: This combined synonym file should be reviewed by a human to ensure accuracy.\n")
        f.write("# Automatic merging of synonyms can sometimes lead to erroneous or misleading synonym sets.\n")
        f.write("# For example, if one file contains:\n")
        f.write("#   bank, financial institution\n")
        f.write("# and another file contains:\n")
        f.write("#   bank, riverbank\n")
        f.write("# The resulting merged line might be:\n")
        f.write("#   bank, financial institution, riverbank\n")
        f.write("# which could lead to confusion in search results. Review these cases carefully.\n\n")

        # Write metadata
        f.write(f"# Files combined:\n")
        for file_path in file_paths:
            f.write(f"# - {file_path}\n")
        f.write(f"\n# Timestamp: {timestamp}\n")
        f.write(f"# User: {user}\n")
        f.write(f"# Hostname: {hostname}\n\n")

        # Write the combined synonym lines
        for line in sorted(combined_synonyms):
            f.write(line + '\n')


def main():
    """
    Main function to combine all synonym files in a specified directory and save the output with a header and metadata.

    :param directory: Directory containing synonym files passed as a command-line argument.
    :param output_file: The output file path where the combined synonyms will be saved.
    """
    if len(sys.argv) != 3:
        print("Usage: python combine_synonyms.py <directory> <output_file>")
        sys.exit(1)

    directory = sys.argv[1]  # Get directory from command line argument
    output_file = sys.argv[2]  # Get output file name from command line argument

    if not os.path.isdir(directory):
        print(f"Error: Directory '{directory}' does not exist.")
        sys.exit(1)

    combined_synonyms, file_paths = combine_synonym_files_in_directory(directory)
    write_combined_synonyms(output_file, combined_synonyms, file_paths)
    print(f"Combined synonyms written to {output_file}")


if __name__ == "__main__":
    main()
